spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 5000
            response-timeout: 10s

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator refresh endpoint
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: "gatwayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG


