spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
       # native:
         # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/bghosh482/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator refresh endpoint
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45@5#5ZXKIEG5%5@5A&3$4%5Z5#33@2"

server:
  port: 8071
